[build]
  publish = "."

# IMPORTANT: the first path includes a * so it matches ?slug=...
[[edge_functions]]
  function = "seo-blog"
  path = "/html/blog-detail.html*"

[[edge_functions]]
  function = "seo-blog"
  path = "/blog/*"
