[build]
  publish = "."

# IMPORTANT: use a glob that matches the path
[[edge_functions]]
  function = "seo-blog"
  path = "/html/blog-detail.html*"

# Optional pretty route once the above works:
# [[edge_functions]]
#   function = "seo-blog"
#   path = "/blog/*"
